### ISSUE TITLE
rqlite does support master forwarding

### ISSUE THREAD

**Issue by otoolep** [raindog308/gorqlite#1]
>>gorqlite always talks to the master (unless it's searching for a master). In theory, you talk to a non-master in "none" consistency mode, but this adds a surprising amount of complexity

I'm not sure I follow this -- why is it complex? If you talk to a non-master node, that node will respond with something like this (from a `curl` session):
```
< HTTP/1.1 301 Moved Permanently
< Location: http://localhost:4001/db/execute
```
Your client simply looks for `Location` and redirects to that node, which is the actual master.

Or do I misunderstand your issue?

**Comment by otoolep** [comment]
By the way, I would be interested in any suggestions you have for making rqlite easier to work with -- simply open issues in the repo.

**Comment by raindog308** [comment]
Sorry, poorly worded on my part.  It's not an issue - more an explanation of how gorqlite works.  I meant to say that handling the one case where an rqlite non-master can satisfy a read introduces complexity **into gorqlite**.

The one case arises if you query with "none" consistency.  If I'm on a non-master and running rqlite on localhost and don't care about consistency, it'll be faster for me to talk to my localhost than to talk over the network to the master.

The way gorqlite works is that whenever it gets a redirect, it just follows it and updates its record of who the master is.  gorqlite always tries to talk to the master.  I could implement logic that would keep track of both a "preferred" node and the master, but that introduces more complexity (as the user can change consistency levels later, the cluster config might change, etc.)  Even with "none", the rqlite intent to me seems aimed more at the master achieving a faster response than having non-masters answer reads (I think).

So it's more a case of "keeping it simple, didn't implement that one special case that may have never been an intended use".

Supporting "none" reads from non-masters could be added as a gorqlite feature.  Is that kind of query something rqlite intends to support, or is "none" more about faster masters?

**Comment by otoolep** [comment]
OK, thanks for the the explanation. `none` isn't really about masters. It's just about letting the node query its local copy, if that is all you want.

**Comment by otoolep** [comment]
My question has been answered.
